###
GET https://jsonplaceholder.typicode.com/posts?userId=1
###
GET https://jsonplaceholder.typicode.com/posts/1
###
POST https://jsonplaceholder.typicode.com/posts

Content-Type: application/json
{
  "title": "AK-47 | Redline",
  "body": "anúncio de teste",
  "userId": 1
}
 
###
GET https://jsonplaceholder.typicode.com/posts/999999
###
GET https://jsonplaceholder.typicode.com/Skins

